name: Google Remote Desktop RDP

on:
  workflow_dispatch:
    inputs:
      crd_setup:
        description: 'Set up Chrome Remote Desktop'
        required: false
        options:
          no:
            description: 'No'
      pin:
        description: 'Enter the 6-digit PIN for Chrome Remote Desktop'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up CRD
      id: crd_setup
      if: ${{ github.event.inputs.crd_setup }}
      run: |
        # Add steps to set up Chrome Remote Desktop
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo dpkg --install chrome-remote-desktop_current_amd64.deb
        sudo apt-get install --assume-yes --fix-broken
        sudo DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes xfce4 desktop-base
        sudo bash -c 'echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session'
        sudo usermod -a -G chrome-remote-desktop $USER
        sudo systemctl disable lightdm.service

    - name: Enter PIN
      if: github.event.inputs.pin
      run: |
        printf "${{ github.event.inputs.pin }}\n${{ github.event.inputs.pin }}\nn\n" | sudo bash /opt/google/chrome-remote-desktop/chrome-remote-desktop --setup
      needs: crd_setup

    - name: Start Remote Desktop Service
      run: |
        sudo /opt/google/chrome-remote-desktop/start-host --code="4/0AdLIrYf-akOyhMbwX4rZ-0tCZEq5bcDwQYGZbn5jHqZv_FsgGyMSecLjrfnNllYWwv_-aQ" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)
        sudo systemctl start chrome-remote-desktop

    - name: Wait for Remote Desktop Service to start
      run: sleep 10

    - name: Install xrdp
      run: sudo apt-get install -y xrdp

    - name: Restart xrdp service
      run: sudo systemctl restart xrdp

    - name: Print IP Address
      run: hostname -I

    - name: Set up ngrok
      uses: w9jds/ngrok-action@v2
      with:
        authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Keep RDP session running
      run: tmux new -d -s RDP 'sudo systemctl restart chrome-remote-desktop.service && sleep 86400'
