name: Google Remote Desktop RDP

on:
  workflow_dispatch:
    inputs:
      pin:
        description: 'Enter the 6-digit PIN for Chrome Remote Desktop'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up CRD
      id: crd_setup
      run: |
        # Add steps to set up Chrome Remote Desktop
        if [ -n "${{ github.event.inputs.pin }}" ]; then
          printf "${{ github.event.inputs.pin }}\n${{ github.event.inputs.pin }}\nn\n" | sudo bash /opt/google/chrome-remote-desktop/chrome-remote-desktop --setup
        fi

    - name: Start Remote Desktop Service
      run: sudo systemctl start chrome-remote-desktop.service

    - name: Wait for Remote Desktop Service to start
      run: sleep 10

    - name: Install xrdp
      run: sudo apt-get install -y xrdp

    - name: Restart xrdp service
      run: sudo systemctl restart xrdp

    - name: Print IP Address
      run: hostname -I

    - name: Set up ngrok
      uses: w9jds/ngrok-action@v2
      with:
        authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Keep RDP session running
      run: tmux new -d -s RDP 'sudo systemctl restart chrome-remote-desktop.service && sleep 86400'
